# Generated by Django 5.2.1 on 2025-05-20 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_description', models.TextField(blank=True)),
                ('machine_type', models.CharField(choices=[('lathe', 'Lathe'), ('mill', 'Mill'), ('grinder', 'Grinder'), ('other', 'Other')], max_length=50)),
                ('machine_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='idle', max_length=20)),
                ('machine_location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=50)),
                ('order_description', models.TextField(blank=True)),
                ('order_date_creation', models.DateTimeField(auto_now_add=True)),
                ('order_date_completion', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_operation', models.CharField(max_length=50)),
                ('task_queue_number', models.PositiveIntegerField()),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_start_time', models.DateTimeField(blank=True, null=True)),
                ('task_finish_time', models.DateTimeField(blank=True, null=True)),
                ('task_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workshop.machine')),
                ('task_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workshop.order')),
            ],
            options={
                'ordering': ['task_queue_number'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('log_message', models.TextField()),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('log_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workshop.task')),
            ],
        ),
    ]
