# Generated by Django 5.2.1 on 2025-05-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['queue_number']},
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='log_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='log_task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='log_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machine_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machine_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machine_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machine_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date_completion',
            new_name='date_completion',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date_creation',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_finish_time',
            new_name='finish_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_machine',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_operation',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_queue_number',
            new_name='queue_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_start_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
    ]
