# Generated by Django 5.2.1 on 2025-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_order_date_start_alter_order_date_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_gap_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
