# Generated by Django 5.2.1 on 2025-05-29 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_alter_machine_maintenance_gap_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 29), null=True),
        ),
    ]
