# Generated by Django 5.2.1 on 2025-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_alter_machine_last_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(auto_now_add=True),
        ),
    ]
