# Generated by Django 5.2.1 on 2025-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_machine_type',
            field=models.CharField(choices=[('lathe', 'Lathe'), ('mill', 'Mill'), ('grinder', 'Grinder'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
