# Generated by Django 5.2.1 on 2025-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_task_required_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='required_machine_type',
            field=models.CharField(choices=[('lathe', 'Lathe'), ('mill', 'Mill'), ('grinder', 'Grinder'), ('other', 'Other')], default=None, max_length=20),
        ),
    ]
