# Generated by Django 5.2.1 on 2025-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_activitylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
