# Generated by Django 5.2.1 on 2025-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_machine_last_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenance_gap_days',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
