# Generated by Django 5.2.1 on 2025-05-29 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_alter_machine_last_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
    ]
