# Generated by Django 5.2.1 on 2025-05-30 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_alter_machine_last_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workshop.task'),
        ),
    ]
